#if !canImport(ObjectiveC)
import XCTest

extension ArxivQueryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArxivQueryTests = [
        ("testEmptyQuery", testEmptyQuery),
        ("testTrimmedQuery", testTrimmedQuery),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArxivQueryTests.__allTests__ArxivQueryTests),
    ]
}
#endif
